name: checks
on: 
  workflow_dispatch:
    inputs:
      crazy:
        type: boolean
        description: "bool"
        default: false
  push:
    branches: [master]
  pull_request:
    branches: [master]


concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  ACT_OWNER: ${{ github.repository_owner }}
  ACT_REPOSITORY: ${{ github.repository }}
  CGO_ENABLED: 0

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          cmd:
            - 'cmd/**'
          pkg:
            - 'pkg/**'

    # run only if 'cmd' files were changed
    - name: cmd tests
      if: steps.filter.outputs.cmd == 'true'
      run: echo "cmd tests"

    # run only if 'pkg' files were changed
    - name: pkg tests
      if: steps.filter.outputs.pkg == 'true'
      run: echo "pkg tests"


